/**
 * Icon constants for consistent icon usage across the application
 * All icons use lucideoslucideor icon library via Iconify
 * Format: i-lucide-{icon-name}
 */
export const ICONS = {
  // Navigation
  DASHBOARD: "i-lucide-layout-dashboard",
  INQUIRIES: "i-lucide-book-open",
  AWARD: "i-lucide-award",
  USERS: "i-lucide-users",
  USER: "i-lucide-user",
  SHIELD_CHECK: "i-lucide-shield-check",
  CONFIGURATION: "i-lucide-gear",
  REPORTS: "i-lucide-chart-bar",
  BRIEFCASE: "i-lucide-briefcase-business",
  DUMBELL: "i-lucide-dumbbell",
  DOOR_LOCK: "i-lucide-door-closed-locked",
  MAILS: "i-lucide-mails",
  BADGE_PERCENT: "i-lucide-badge-percent",
  USER_COG: "i-lucide-user-cog",
  USER_PEN: "i-lucide-user-pen",
  INFO: "i-lucide-info",
  THREE_VERTICAL_DOTS: "i-lucide-ellipsis-vertical",

  // Actions
  EYE: "i-lucide-eye",
  EYE_OFF: "i-lucide-eye-off",
  PLUS: "i-lucide-plus",
  EDIT: "i-lucide-pencil",
  COPY: "i-lucide-copy",
  CLIPBOARD_CHECK: "i-lucide-clipboard-check",
  SETTINGS: "i-lucide-settings",
  LOGOUT: "i-lucide-log-out",
  LOCK: "i-lucide-lock",
  CHECK: "i-lucide-check",
  CHECK_CIRCLE: "i-lucide-check-circle",
  BADGE_CHECK: "i-lucide-badge-check",
  X: "i-lucide-x",
  X_CIRCLE: "i-lucide-x-circle",
  BAN: "i-lucide-prohibit",
  X_OCTAGON: "i-lucide-octagon",
  ALERT_CIRCLE: "i-lucide-warning-circle",
  PEN_LINE: "i-lucide-pen-line",
  TRASH_2: "i-lucide-trash-2",
  DOWNLOAD: "i-lucide-download",
  WARNING: "i-lucide-triangle-alert",
  WIFI: "i-lucide-wifi",
  BANKNOTE: "i-lucide-banknote",
  TRASH: "i-lucide-trash-2",
  USER_PLUS: "i-lucide-user-plus",
  ID_CARD: "i-lucide-id-card-lanyard",
  MONEY: "i-lucide-banknote",
  LOADING: "i-lucide-loader",

  // UI Elements
  ELLIPSIS_VERTICAL: "i-lucide-ellipsis-vertical",
  PANEL_RIGHT: "i-lucide-panel-right",
  SIDEBAR_TOGGLE: "i-lucide-list",
  CALENDAR: "i-lucide-calendar",
  TRENDING_UP: "i-lucide-trend-up",
  TRENDING_DOWN: "i-lucide-trend-down",
  lucideONE: "i-lucide-lucideone",
  MAIL: "i-lucide-envelope",
  MAP_PIN: "i-lucide-map-pin",
  BUILDING: "i-lucide-buildings",
  CLOCK: "i-lucide-clock",
  SEARCH: "i-lucide-search",
  SUBSCRIPTIONS: "i-lucide-currency-dollar",
  CREDIT_CARD: "i-lucide-credit-card",
  COUPONS: "i-lucide-ticket",
  BILLING: "i-lucide-hand-coins",
  LIST: "i-lucide-list",
  PLAY: "i-lucide-play",
  UPLOAD: "i-lucide-upload",
  REFRESH_CW: "i-lucide-refresh-ccw",
  NOTIFICATION: "i-lucide-bell",
  CHART_LINE: "i-lucide-chart-line",
  LOCATION: "i-lucide-map-pin",
  PRICE: "i-lucide-dollar-sign",
  CAPACITY: "i-lucide-users",
  REGISTERED: "i-lucide-user-check",
  SAVE: "i-lucide-save",
  FLOWER: "i-lucide-flower",
  IMAGE: "i-lucide-image",
  CIRCLE_CHECK: "i-lucide-circle-check",
  FILE: "i-lucide-file",

  // arrow
  ARROW_LEFT: "i-lucide-arrow-left",
  ARROW_RIGHT: "i-lucide-arrow-right",
  ARROW_UP: "i-lucide-arrow-up",
  ARROW_DOWN: "i-lucide-arrow-down",

} as const;
