/**
 * Permission keys for feature gating.
 * Must match the module `name` values from the backend (system_modules seed).
 * API returns these in auth/me data.permissions.
 */

// ——— Top-level modules ———
export const PERMISSIONS = {
  INQUIRIES: "INQUIRIES",
  COMMUNITIES: "COMMUNITIES",
  TRANSACTIONS: "TRANSACTIONS",
  ADMINS: "ADMINS",
  CONFIGURATION: "CONFIGURATION",
  REPORTS: "REPORTS",
} as const;

// ——— Inquiries ———
export const PERMISSIONS_INQUIRIES = {
  SEARCH: "INQUIRIES.SEARCH",
  CREATE: "INQUIRIES.CREATE",
  VIEW: "INQUIRIES.VIEW",
  VIEW_INFO: "INQUIRIES.VIEW.INFO",
  VIEW_ONBOARDING: "INQUIRIES.VIEW.ONBOARDING",
} as const;

// ——— Communities ———
export const PERMISSIONS_COMMUNITIES = {
  CREATE: "COMMUNITIES.CREATE",
  VIEW: "COMMUNITIES.VIEW",
  VIEW_INFO: "COMMUNITIES.VIEW.INFO",
  VIEW_ACCOUNT: "COMMUNITIES.VIEW.ACCOUNT",
  VIEW_USAGE: "COMMUNITIES.VIEW.USAGE",
  VIEW_ADMINS: "COMMUNITIES.VIEW.ADMINS",
  VIEW_ACCOUNT_UPDATE: "COMMUNITIES.VIEW.ACCOUNT.UPDATE",
} as const;

// ——— Transactions ———
export const PERMISSIONS_TRANSACTIONS = {
  CREATE: "TRANSACTIONS.CREATE",
  CREATE_SUBSCRIPTION: "TRANSACTIONS.CREATE.SUBSCRIPTION",
  CREATE_NEW: "TRANSACTIONS.CREATE.NEW",
  LIST: "TRANSACTIONS.LIST",
  LIST_SEARCH: "TRANSACTIONS.LIST.SEARCH",
  LIST_VIEW: "TRANSACTIONS.LIST.VIEW",
  LIST_PAY: "TRANSACTIONS.LIST.PAY",
  LIST_CANCEL: "TRANSACTIONS.LIST.CANCEL",
  PAYMENT: "TRANSACTIONS.PAYMENT",
  PAYMENT_SEARCH: "TRANSACTIONS.PAYMENT.SEARCH",
  PAYMENT_VIEW: "TRANSACTIONS.PAYMENT.VIEW",
} as const;

// ——— Admins ———
export const PERMISSIONS_ADMINS = {
  ROLES_PERMISSIONS: "ADMINS.ROLES_PERMISSIONS",
  ROLES_PERMISSIONS_ADD_ROLE: "ADMINS.ROLES_PERMISSIONS.ADD_ROLE",
  ROLES_PERMISSIONS_UPDATE: "ADMINS.ROLES_PERMISSIONS.UPDATE_PERMISSIONS",
  LIST: "ADMINS.LIST",
  LIST_SEARCH: "ADMINS.LIST.SEARCH",
  LIST_VIEW: "ADMINS.LIST.VIEW",
  LIST_ADD: "ADMINS.LIST.ADD",
  LIST_UPDATE: "ADMINS.LIST.UPDATE",
} as const;

// ——— Configuration ———
export const PERMISSIONS_CONFIGURATION = {
  PLANS: "CONFIGURATION.PLANS",
  PLANS_SEARCH: "CONFIGURATION.PLANS.SEARCH",
  PLANS_VIEW: "CONFIGURATION.PLANS.VIEW",
  PLANS_ADD: "CONFIGURATION.PLANS.ADD",
  PLANS_UPDATE: "CONFIGURATION.PLANS.UPDATE",
  BILLABLE_ITEMS: "CONFIGURATION.BILLABLE_ITEMS",
  BILLABLE_ITEMS_SEARCH: "CONFIGURATION.BILLABLE_ITEMS.SEARCH",
  BILLABLE_ITEMS_VIEW: "CONFIGURATION.BILLABLE_ITEMS.VIEW",
  BILLABLE_ITEMS_ADD: "CONFIGURATION.BILLABLE_ITEMS.ADD",
  BILLABLE_ITEMS_UPDATE: "CONFIGURATION.BILLABLE_ITEMS.UPDATE",
  COUPONS: "CONFIGURATION.COUPONS",
  COUPONS_SEARCH: "CONFIGURATION.COUPONS.SEARCH",
  COUPONS_VIEW: "CONFIGURATION.COUPONS.VIEW",
  COUPONS_ADD: "CONFIGURATION.COUPONS.ADD",
  COUPONS_UPDATE: "CONFIGURATION.COUPONS.UPDATE",
  PAYMENT_METHODS: "CONFIGURATION.PAYMENT_METHODS",
  PAYMENT_METHODS_ADD_CATEGORY: "CONFIGURATION.PAYMENT_METHODS.ADD_CATEGORY",
  PAYMENT_METHODS_ADD_METHOD: "CONFIGURATION.PAYMENT_METHODS.ADD_METHOD",
} as const;

/** Flat map of all permission strings for sidebar and simple checks. */
export const PERMISSIONS_NAV = {
  DASHBOARD: null as string | null, // no permission, always visible
  INQUIRIES: PERMISSIONS.INQUIRIES,
  COMMUNITIES_CREATE: PERMISSIONS_COMMUNITIES.CREATE,
  COMMUNITIES_VIEW: PERMISSIONS_COMMUNITIES.VIEW,
  TRANSACTIONS_CREATE: PERMISSIONS_TRANSACTIONS.CREATE,
  TRANSACTIONS_LIST: PERMISSIONS_TRANSACTIONS.LIST,
  TRANSACTIONS_PAYMENT: PERMISSIONS_TRANSACTIONS.PAYMENT,
  REPORTS: PERMISSIONS.REPORTS,
  ADMINS_ROLES_PERMISSIONS: PERMISSIONS_ADMINS.ROLES_PERMISSIONS,
  ADMINS_LIST: PERMISSIONS_ADMINS.LIST,
  CONFIGURATION_PLANS: PERMISSIONS_CONFIGURATION.PLANS,
  CONFIGURATION_BILLABLE_ITEMS: PERMISSIONS_CONFIGURATION.BILLABLE_ITEMS,
  CONFIGURATION_COUPONS: PERMISSIONS_CONFIGURATION.COUPONS,
  CONFIGURATION_PAYMENT_METHODS: PERMISSIONS_CONFIGURATION.PAYMENT_METHODS,
} as const;

export type PermissionKey
  = | typeof PERMISSIONS[keyof typeof PERMISSIONS]
    | typeof PERMISSIONS_INQUIRIES[keyof typeof PERMISSIONS_INQUIRIES]
    | typeof PERMISSIONS_COMMUNITIES[keyof typeof PERMISSIONS_COMMUNITIES]
    | typeof PERMISSIONS_TRANSACTIONS[keyof typeof PERMISSIONS_TRANSACTIONS]
    | typeof PERMISSIONS_ADMINS[keyof typeof PERMISSIONS_ADMINS]
    | typeof PERMISSIONS_CONFIGURATION[keyof typeof PERMISSIONS_CONFIGURATION];
